enroll/urls.py
from django.urls import path
from . import views
from enroll import views

app_name='enroll'
urlpatterns = [
   
    path('', views.base1, name="base1"),
    path('addandshow', views.add_show, name="addandshow"),
    #path('base1/', views.add_show2, name="addandshow2"),
    path('delete/<int:id>/', views.delete_data, name="deletedata"),
    path('<int:id>/', views.update_data, name="updatedata"),
    
    
    
]

teaching_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from enroll import views
import app_users
import curriculum
import enroll
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('', include('app_users.urls')),
    path('curriculum/',include('curriculum.urls')),
    path('admin/', admin.site.urls),
    path('enroll/',include('enroll.urls')),
    path('enroll', views.base1, name="base1"),    
    path('addandshow', views.add_show, name="addandshow"),
    #path('enroll/', views.add_show2, name="addandshow2"),
    path('delete/<int:id>/', views.delete_data, name="deletedata"),
    path('<int:id>/', views.update_data, name="updatedata"),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

enroll/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    token_number = models.CharField(max_length=70)
    name = models.CharField(max_length=70)
    section_sem = models.CharField(max_length=70)

enroll/forms.py
from django.core import validators
from django import forms
from django.forms import fields, widgets
from django.shortcuts import render 
from .models import User

class StudentRegistration(forms.ModelForm):
    class Meta:
        model = User
        fields = ['token_number','name','section_sem']
        widgets = {
            'token_name' : forms.TextInput(attrs={'class':'form-control'}),
            'name' : forms.TextInput(attrs={'class':'form-control'}),
            'section_sem' : forms.TextInput({'class':'form-control'}),
        } 
        
#'section_sem' : forms.TextInput("""render_value=True,""" attrs={'class':'form-control'}),        

enroll/views.py
from typing import ValuesView
from django.http import request
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, HttpResponse
from .forms import StudentRegistration
from .models import User
from django.shortcuts import render
# Create your views here.
from django.urls import reverse_lazy

# for add new data and sho
def add_show(request):
    if request.method =='GET':
        return render(request,'enroll/addandshow.html')
        #return render(request,'enroll/base1.html')

def add_show2(request):
    if request.method =='GET':
        return render(request,'enroll/select.html')

def base1(request):
    if request.method =='POST':
        fm = StudentRegistration(request.POST)
        if fm.is_valid():
            tn=fm.cleaned_data['token_number']
            nm=fm.cleaned_data['name']
            ss=fm.cleaned_data['section_sem']
            
            reg= User(token_number=tn,name=nm,section_sem=ss)
            reg.save()
            fm= StudentRegistration()
    else:
        fm = StudentRegistration()
    stud = User.objects.all()
    return render(request,'enroll/addandshow.html',{'form':fm,'stu':stud})
#to update
def update_data(request,id):
    if request.method == 'POST':
        pi=User.objects.get(pk=id)
        fm = StudentRegistration(request.POST, instance=pi)
        if fm.is_valid():
            fm.save()
    else:
        pi=User.objects.get(pk=id)
        fm = StudentRegistration(instance=pi)
    return render(request,'enroll/updatestudent.html', {'form':id})



#to delete
def delete_data(request,id):
    if request.method == 'POST':
        pi = User.objects.get(pk=id)
        pi.delete()
        return HttpResponseRedirect('/')

enroll/templates/enroll/addandshow.html
{% extends 'enroll/base1.html' %} {% block content %}
<div class="row">
    <div class="col-sm-4">
        <h4 class="text-center alert alert-info">Add New Student </h4>
        <form action="" method="POST">
            {%csrf_token %} {{ form.as_p}}
            <input type="submit" class="btn btn-success" value="Add   ">
        </form>
    </div>

    <div class="col-sm-7 offset-1">
        <h4 class="text-center alert alert-info">show students info </h4>


        {% if stu %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Token_number</th>
                    <th scope="col">Name</th>
                    <th scope="col">Section_sem</th>
                    <th scope="col">action</th>
                </tr>
            </thead>
            <tbody>
                {% for st in stu %}
                <tr>
                    <th scope="row">{{st.id}}</th>
                    <td>{{st.token_number}}</td>
                    <td>{{st.name}}</td>
                    <td>{{st.section_sem}}</td>
                    <td>
                        <a href="{% url 'updatedata' st.id %}" class="btn btn-warning btn-sm">Edit</a>
                        <form action="{% url 'deletedata' st.id %}" method="post" class="d-inline"> {% csrf_token %}
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>


        {% else %}
        <h4 class="text-center alert alert-warning">No Records </h4>
        {% endif %}
    </div>
</div>
{%endblock content%}

enroll/templates/enroll/base1.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
    initial-scale=1.0">
    <title>Add Student Data</title>
    <link rel="stylesheet" href="{%static 'enroll/css/bootstrap.css'%}">

</html>


<body>
    <div class="container mt-5">
        <h2 class="text-center alert alert-danger">To Update or View student data</h2>
        {% block content %} {% endblock content%}
    </div>
    <script src="{% static 'enroll/js/jquery.js' %}"></script>
    <script src="{% static 'enroll/js/popper.js' %}"></script>
    <script src="{% static 'enroll/js/bootstrap.js' %}"></script>
</body>

</html>

enroll/templates/enroll/select.html
<!DOCTYPE html>
<html>

<body>

    <h1>Select your Sem</h1>
    <p>Here to see the batch student Data.</p>

</body>
<li class="nav-item ">
    <a class="nav-link" href="{% url 'enroll:addandshow' %}">1st year</span> </a>
</li>
<li class="nav-item ">
    <a class="nav-link" href="{% url 'enroll:base1' %}">2st year</span> </a>
</li>
<li class="nav-item ">
    <a class="nav-link" href="{% url 'enroll:base1' %}">3st year</span> </a>
</li>

</html>

enroll/templates/enroll/updatestudent.html
{% extends 'enroll/base1.html' %} {% block content %}

<div class="row">
    <div class="col-sm-8 offset-2">
        <h4 class="alert alert-info">Update Student Information</h4>
        <form action="" method="POST">
            {% csrf_token %} {{form.as_p}}
            <input type="submit" class="btn btn-success" value="Update">
            <a href="{% url 'enroll' %}" class="btn btn-info">Back to home</a>
        </form>
    </div>
</div>

{%endblock content%}